package dev.inboxbridge.web.oauth;

import java.util.Map;

public final class OAuthPageI18n {

    private static final Map<String, Map<String, String>> TRANSLATIONS = Map.ofEntries(
            entry("Google OAuth Callback", "Retour OAuth Google", "Google OAuth-Rueckruf", "Retorno do Google OAuth", "Retorno do Google OAuth", "Retorno de Google OAuth"),
            entry("Google OAuth Code Received", "Code OAuth Google recu", "Google-OAuth-Code empfangen", "Codigo do Google OAuth recebido", "Codigo do Google OAuth recebido", "Codigo de Google OAuth recibido"),
            entry("Microsoft OAuth Code Received", "Code OAuth Microsoft recu", "Microsoft-OAuth-Code empfangen", "Codigo do Microsoft OAuth recebido", "Codigo do Microsoft OAuth recebido", "Codigo de Microsoft OAuth recibido"),
            entry("Copy Code", "Copier le code", "Code kopieren", "Copiar codigo", "Copiar codigo", "Copiar codigo"),
            entry("Exchange Code In Browser", "Echanger le code dans le navigateur", "Code im Browser austauschen", "Trocar codigo no browser", "Trocar codigo no browser", "Intercambiar codigo en el navegador"),
            entry("Cancel automatic redirect", "Annuler la redirection automatique", "Automatische Weiterleitung abbrechen", "Cancelar redirecionamento automatico", "Cancelar redirecionamento automatico", "Cancelar la redireccion automatica"),
            entry("Return to InboxBridge", "Retourner a InboxBridge", "Zu InboxBridge zurueckkehren", "Voltar ao InboxBridge", "Voltar ao InboxBridge", "Volver a InboxBridge"),
            entry("(no authorization code received)", "(aucun code d'autorisation recu)", "(kein Autorisierungscode empfangen)", "(nenhum codigo de autorizacao recebido)", "(nenhum codigo de autorizacao recebido)", "(no se recibio ningun codigo de autorizacion)"),
            entry("Redirecting to InboxBridge in ", "Redirection vers InboxBridge dans ", "Weiterleitung zu InboxBridge in ", "A redirecionar para o InboxBridge em ", "Redirecionando para o InboxBridge em ", "Redirigiendo a InboxBridge en "),
            entry(" seconds.", " secondes.", " Sekunden.", " segundos.", " segundos.", " segundos."),
            entry("Redirecting to InboxBridge now...", "Redirection vers InboxBridge maintenant...", "Weiterleitung zu InboxBridge jetzt...", "A redirecionar para o InboxBridge agora...", "Redirecionando para o InboxBridge agora...", "Redirigiendo a InboxBridge ahora..."),
            entry("No authorization code is available to copy from this callback URL.", "Aucun code d'autorisation n'est disponible a copier depuis cette URL de retour.", "Es ist kein Autorisierungscode verfuegbar, der aus dieser Callback-URL kopiert werden kann.", "Nao existe nenhum codigo de autorizacao disponivel para copiar deste URL de retorno.", "Nao existe nenhum codigo de autorizacao disponivel para copiar desta URL de retorno.", "No hay ningun codigo de autorizacion disponible para copiar desde esta URL de retorno."),
            entry("Authorization code copied to clipboard.", "Code d'autorisation copie dans le presse-papiers.", "Autorisierungscode in die Zwischenablage kopiert.", "Codigo de autorizacao copiado para a area de transferencia.", "Codigo de autorizacao copiado para a area de transferencia.", "Codigo de autorizacion copiado al portapapeles."),
            entry("Unable to copy automatically. Copy the code manually before leaving this page.", "Copie automatique impossible. Copiez le code manuellement avant de quitter cette page.", "Automatisches Kopieren nicht moeglich. Kopieren Sie den Code manuell, bevor Sie diese Seite verlassen.", "Nao foi possivel copiar automaticamente. Copie o codigo manualmente antes de sair desta pagina.", "Nao foi possivel copiar automaticamente. Copie o codigo manualmente antes de sair desta pagina.", "No se pudo copiar automaticamente. Copie el codigo manualmente antes de salir de esta pagina."),
            entry("Google OAuth is still missing one or more required permissions. Retry the flow and approve every requested Gmail permission, then try again. Details: ", "Il manque encore une ou plusieurs autorisations requises a Google OAuth. Relancez le flux et acceptez toutes les autorisations Gmail demandees. Details : ", "Google OAuth fehlen weiterhin eine oder mehrere erforderliche Berechtigungen. Starten Sie den Vorgang erneut und genehmigen Sie alle angeforderten Gmail-Berechtigungen. Details: ", "Ainda falta uma ou mais permissoes obrigatorias no Google OAuth. Repita o processo e aceite todas as permissoes pedidas do Gmail. Detalhes: ", "Ainda falta uma ou mais permissoes obrigatorias no Google OAuth. Repita o processo e aceite todas as permissoes pedidas do Gmail. Detalhes: ", "A Google OAuth todavia le faltan uno o mas permisos obligatorios. Repita el proceso y acepte todos los permisos de Gmail solicitados. Detalles: "),
            entry("Microsoft OAuth is still missing one or more required permissions. Retry the flow and approve every requested mailbox permission, then try again. Details: ", "Il manque encore une ou plusieurs autorisations requises a Microsoft OAuth. Relancez le flux et acceptez toutes les autorisations de boite mail demandees. Details : ", "Microsoft OAuth fehlen weiterhin eine oder mehrere erforderliche Berechtigungen. Starten Sie den Vorgang erneut und genehmigen Sie alle angeforderten Postfach-Berechtigungen. Details: ", "Ainda falta uma ou mais permissoes obrigatorias no Microsoft OAuth. Repita o processo e aceite todas as permissoes pedidas da caixa de correio. Detalhes: ", "Ainda falta uma ou mais permissoes obrigatorias no Microsoft OAuth. Repita o processo e aceite todas as permissoes pedidas da caixa de correio. Detalhes: ", "A Microsoft OAuth todavia le faltan uno o mas permisos del buzon solicitados. Detalles: "),
            entry("Exchange failed: ", "La conversion du code a echoue : ", "Der Code-Austausch ist fehlgeschlagen: ", "A troca do codigo falhou: ", "A troca do codigo falhou: ", "El intercambio del codigo fallo: "),
            entry("OAuth returned ", "OAuth a renvoye ", "OAuth gab zurueck ", "O OAuth devolveu ", "O OAuth devolveu ", "OAuth devolvio "),
            entry("Microsoft OAuth returned ", "Microsoft OAuth a renvoye ", "Microsoft OAuth gab zurueck ", "O Microsoft OAuth devolveu ", "O Microsoft OAuth devolveu ", "Microsoft OAuth devolvio "),
            entry("No authorization code was present in the callback URL.", "Aucun code d'autorisation n'etait present dans l'URL de retour.", "In der Callback-URL war kein Autorisierungscode vorhanden.", "Nao foi encontrado qualquer codigo de autorizacao no URL de retorno.", "Nao foi encontrado nenhum codigo de autorizacao na URL de retorno.", "No se encontro ningun codigo de autorizacion en la URL de retorno."),
            entry("Exchanging authorization code...", "Echange du code d'autorisation...", "Autorisierungscode wird ausgetauscht...", "A trocar o codigo de autorizacao...", "Trocando o codigo de autorizacao...", "Intercambiando el codigo de autorizacion..."),
            entry("Storage: ", "Armazenamento: ", "Speicher: ", "Armazenamento: ", "Armazenamento: ", "Almacenamiento: "),
            entry("Encrypted storage", "Stockage chiffre", "Verschluesselte Speicherung", "Armazenamento encriptado", "Armazenamento criptografado", "Almacenamiento cifrado"),
            entry("Environment fallback", "Repli sur l'environnement", "Umgebungs-Fallback", "Fallback por ambiente", "Fallback por ambiente", "Alternativa por entorno"),
            entry("Previous Gmail account replaced: ", "Compte Gmail precedent remplace : ", "Vorheriges Gmail-Konto ersetzt: ", "Conta Gmail anterior substituida: ", "Conta Gmail anterior substituida: ", "Cuenta de Gmail anterior sustituida: "),
            entry("Same Gmail account reauthorized: ", "Meme compte Gmail reautorise : ", "Dasselbe Gmail-Konto erneut autorisiert: ", "Mesma conta Gmail reautorizada: ", "Mesma conta Gmail reautorizada: ", "La misma cuenta de Gmail fue autorizada de nuevo: "),
            entry("Previous Google grant revoked: ", "Autorisation Google precedente revoquee : ", "Vorherige Google-Berechtigung widerrufen: ", "Permissao Google anterior revogada: ", "Permissao Google anterior revogada: ", "Permiso anterior de Google revocado: "),
            entry("Yes", "Oui", "Ja", "Sim", "Sim", "Si"),
            entry("No", "Non", "Nein", "Nao", "Nao", "No"),
            entry("Credential Key: ", "Cle d'identification : ", "Anmeldeschluessel: ", "Chave da credencial: ", "Chave da credencial: ", "Clave de la credencial: "),
            entry("Scope: ", "Portee : ", "Bereich: ", "Escopo: ", "Escopo: ", "Alcance: "),
            entry("Token Type: ", "Type de jeton : ", "Token-Typ: ", "Tipo de token: ", "Tipo de token: ", "Tipo de token: "),
            entry("Access Token Expires At: ", "Le jeton d'acces expire le : ", "Zugriffstoken laeuft ab am: ", "Token de acesso expira em: ", "Token de acesso expira em: ", "El token de acceso vence en: "),
            entry("Next Step: ", "Etape suivante : ", "Naechster Schritt: ", "Proximo passo: ", "Proximo passo: ", "Siguiente paso: "),
            entry("Refresh Token: ", "Jeton d'actualisation : ", "Aktualisierungstoken: ", "Refresh token: ", "Refresh token: ", "Token de actualizacion: "),
            entry("Exchange completed. The same Gmail account was reauthorized, so the existing Google grant was kept in place.", "Echange termine. Le meme compte Gmail a ete reautorise, donc l'autorisation Google existante a ete conservee.", "Austausch abgeschlossen. Dasselbe Gmail-Konto wurde erneut autorisiert, daher blieb die bestehende Google-Berechtigung erhalten.", "Troca concluida. A mesma conta Gmail foi reautorizada, por isso a permissao Google existente foi mantida.", "Troca concluida. A mesma conta Gmail foi reautorizada, por isso a permissao Google existente foi mantida.", "Intercambio completado. La misma cuenta de Gmail fue autorizada de nuevo, por lo que se mantuvo el permiso de Google existente."),
            entry("Exchange completed. The token was stored securely. The previously linked Gmail account was automatically unlinked and its Google grant was revoked.", "Echange termine. Le jeton a ete stocke de maniere securisee. Le compte Gmail precedemment lie a ete delie automatiquement et son autorisation Google a ete revoquee.", "Austausch abgeschlossen. Das Token wurde sicher gespeichert. Das zuvor verknuepfte Gmail-Konto wurde automatisch getrennt und seine Google-Berechtigung widerrufen.", "Troca concluida. O token foi guardado de forma segura. A conta Gmail anteriormente ligada foi desligada automaticamente e a permissao Google foi revogada.", "Troca concluida. O token foi guardado de forma segura. A conta Gmail anteriormente ligada foi desligada automaticamente e a permissao Google foi revogada.", "Intercambio completado. El token se guardo de forma segura. La cuenta de Gmail vinculada anteriormente se desvinculo automaticamente y su permiso de Google fue revocado."),
            entry("Exchange completed. The token was stored securely. The previously linked Gmail account was replaced here, but you may still need to remove the old Google grant manually from myaccount.google.com.", "Echange termine. Le jeton a ete stocke de maniere securisee. Le compte Gmail precedemment lie a ete remplace ici, mais vous devrez peut-etre supprimer manuellement l'ancienne autorisation Google depuis myaccount.google.com.", "Austausch abgeschlossen. Das Token wurde sicher gespeichert. Das zuvor verknuepfte Gmail-Konto wurde hier ersetzt, aber moeglicherweise muessen Sie die alte Google-Berechtigung noch manuell unter myaccount.google.com entfernen.", "Troca concluida. O token foi guardado de forma segura. A conta Gmail anteriormente ligada foi substituida aqui, mas pode ainda ser necessario remover manualmente a permissao Google antiga em myaccount.google.com.", "Troca concluida. O token foi guardado de forma segura. A conta Gmail anteriormente ligada foi substituida aqui, mas pode ainda ser necessario remover manualmente a permissao Google antiga em myaccount.google.com.", "Intercambio completado. El token se guardo de forma segura. La cuenta de Gmail vinculada anteriormente fue sustituida aqui, pero puede que aun necesite eliminar manualmente el permiso antiguo de Google en myaccount.google.com."),
            entry("Exchange completed. The token was stored securely.", "Echange termine. Le jeton a ete stocke de maniere securisee.", "Austausch abgeschlossen. Das Token wurde sicher gespeichert.", "Troca concluida. O token foi guardado de forma segura.", "Troca concluida. O token foi guardado de forma segura.", "Intercambio completado. El token se guardo de forma segura."),
            entry("Exchange completed. The same Gmail account was reauthorized. Copy the refresh token into your local .env if you are using env fallback.", "Echange termine. Le meme compte Gmail a ete reautorise. Copiez le jeton d'actualisation dans votre .env local si vous utilisez le repli sur l'environnement.", "Austausch abgeschlossen. Dasselbe Gmail-Konto wurde erneut autorisiert. Kopieren Sie das Aktualisierungstoken in Ihre lokale .env, wenn Sie den Umgebungs-Fallback verwenden.", "Troca concluida. A mesma conta Gmail foi reautorizada. Copie o refresh token para o seu .env local se estiver a usar fallback por ambiente.", "Troca concluida. A mesma conta Gmail foi reautorizada. Copie o refresh token para o seu .env local se estiver a usar fallback por ambiente.", "Intercambio completado. La misma cuenta de Gmail fue autorizada de nuevo. Copie el token de actualizacion en su .env local si esta usando la alternativa por entorno."),
            entry("Exchange completed. The previously linked Gmail account was replaced. Copy the new refresh token into your local .env if you are using env fallback.", "Echange termine. Le compte Gmail precedemment lie a ete remplace. Copiez le nouveau jeton d'actualisation dans votre .env local si vous utilisez le repli sur l'environnement.", "Austausch abgeschlossen. Das zuvor verknuepfte Gmail-Konto wurde ersetzt. Kopieren Sie das neue Aktualisierungstoken in Ihre lokale .env, wenn Sie den Umgebungs-Fallback verwenden.", "Troca concluida. A conta Gmail anteriormente ligada foi substituida. Copie o novo refresh token para o seu .env local se estiver a usar fallback por ambiente.", "Troca concluida. A conta Gmail anteriormente ligada foi substituida. Copie o novo refresh token para o seu .env local se estiver a usar fallback por ambiente.", "Intercambio completado. La cuenta de Gmail vinculada anteriormente fue sustituida. Copie el nuevo token de actualizacion en su .env local si esta usando la alternativa por entorno."),
            entry("Exchange completed. Copy the refresh token into your local .env if you are using env fallback.", "Echange termine. Copiez le jeton d'actualisation dans votre .env local si vous utilisez le repli sur l'environnement.", "Austausch abgeschlossen. Kopieren Sie das Aktualisierungstoken in Ihre lokale .env, wenn Sie den Umgebungs-Fallback verwenden.", "Troca concluida. Copie o refresh token para o seu .env local se estiver a usar fallback por ambiente.", "Troca concluida. Copie o refresh token para o seu .env local se estiver a usar fallback por ambiente.", "Intercambio completado. Copie el token de actualizacion en su .env local si esta usando la alternativa por entorno."),
            entry("Exchange failed. Check the server logs and OAuth client settings.", "L'echange a echoue. Verifiez les journaux du serveur et les parametres du client OAuth.", "Austausch fehlgeschlagen. Pruefen Sie die Serverprotokolle und die OAuth-Client-Einstellungen.", "A troca do codigo falhou. Verifique os logs do servidor e as definicoes do cliente OAuth.", "A troca do codigo falhou. Verifique os logs do servidor e as definicoes do cliente OAuth.", "El intercambio fallo. Revise los registros del servidor y la configuracion del cliente OAuth."),
            entry("Authorization code received. Attempting automatic exchange...", "Code d'autorisation recu. Tentative d'echange automatique...", "Autorisierungscode empfangen. Automatischer Austausch wird versucht...", "Codigo de autorizacao recebido. A tentar a troca automatica...", "Codigo de autorizacao recebido. Tentando o intercambio automatico...", "Codigo de autorizacion recibido. Intentando el intercambio automatico..."),
            entry("Automatic redirect canceled. You can stay on this page and inspect the exchange details.", "Redirection automatique annulee. Vous pouvez rester sur cette page et consulter les details de l'echange.", "Automatische Weiterleitung abgebrochen. Sie koennen auf dieser Seite bleiben und die Austauschdetails pruefen.", "Redirecionamento automatico cancelado. Pode permanecer nesta pagina e verificar os detalhes da troca.", "Redirecionamento automatico cancelado. Voce pode permanecer nesta pagina e verificar os detalhes da troca.", "Redireccion automatica cancelada. Puede quedarse en esta pagina y revisar los detalles del intercambio."),
            entry("Authorization code received, but callback state is missing. Use the exchange button if you are completing a manual flow.", "Code d'autorisation recu, mais l'etat du rappel manque. Utilisez le bouton d'echange si vous terminez un flux manuel.", "Autorisierungscode empfangen, aber der Callback-Status fehlt. Verwenden Sie die Austausch-Schaltflaeche, wenn Sie einen manuellen Ablauf abschliessen.", "Codigo de autorizacao recebido, mas o estado do retorno esta em falta. Use o botao de troca se estiver a completar um processo manual.", "Codigo de autorizacao recebido, mas o estado do retorno esta faltando. Use o botao de intercambio se estiver concluindo um fluxo manual.", "Codigo de autorizacion recibido, pero falta el estado del retorno. Use el boton de intercambio si esta completando un flujo manual."),
            entry("Leave this page without exchanging the code? You will need to add it manually later.", "Quitter cette page sans echanger le code ? Vous devrez l'ajouter manuellement plus tard.", "Diese Seite verlassen, ohne den Code auszutauschen? Sie muessen ihn spaeter manuell hinzufuegen.", "Sair desta pagina sem trocar o codigo? Vai ter de o adicionar manualmente mais tarde.", "Sair desta pagina sem trocar o codigo? Voce precisara adiciona-lo manualmente depois.", "Salir de esta pagina sin intercambiar el codigo? Tendra que agregarlo manualmente mas tarde."),
            entry("Leave this page without exchanging the code? If you continue, you will need to add it manually from InboxBridge later.", "Quitter cette page sans echanger le code ? Si vous continuez, vous devrez l'ajouter manuellement depuis InboxBridge plus tard.", "Diese Seite verlassen, ohne den Code auszutauschen? Wenn Sie fortfahren, muessen Sie ihn spaeter manuell in InboxBridge hinzufuegen.", "Sair desta pagina sem trocar o codigo? Se continuar, vai ter de o adicionar manualmente mais tarde a partir do InboxBridge.", "Sair desta pagina sem trocar o codigo? Se continuar, sera necessario adiciona-lo manualmente depois a partir do InboxBridge.", "Salir de esta pagina sin intercambiar el codigo? Si continua, tendra que agregarlo manualmente despues desde InboxBridge."),
            entry("Exchange the code here, or copy it before leaving so you can add it manually later.", "Echangez le code ici, ou copiez-le avant de quitter afin de pouvoir l'ajouter manuellement plus tard.", "Tauschen Sie den Code hier aus oder kopieren Sie ihn, bevor Sie die Seite verlassen, damit Sie ihn spaeter manuell hinzufuegen koennen.", "Troque o codigo aqui, ou copie-o antes de sair para o poder adicionar manualmente mais tarde.", "Troque o codigo aqui, ou copie-o antes de sair para poder adiciona-lo manualmente mais tarde.", "Intercambie el codigo aqui, o copielo antes de salir para poder agregarlo manualmente despues."),
            entry("Copy Authorization Code", "Copier le code d'autorisation", "Autorisierungscode kopieren", "Copiar codigo de autorizacao", "Copiar codigo de autorizacao", "Copiar codigo de autorizacion"),
            entry("Copy Env Assignment", "Copier l'affectation d'environnement", "Umgebungszuweisung kopieren", "Copiar atribuicao de ambiente", "Copiar atribuicao de ambiente", "Copiar asignacion de entorno"),
            entry("Exchange Result", "Resultat de l'echange", "Austauschergebnis", "Resultado da troca", "Resultado da troca", "Resultado del intercambio"),
            entry("Env Assignment", "Affectation d'environnement", "Umgebungszuweisung", "Atribuicao de ambiente", "Atribuicao de ambiente", "Asignacion de entorno"),
            entry("Authorization code", "Code d'autorisation", "Autorisierungscode", "Codigo de autorizacao", "Codigo de autorizacao", "Codigo de autorizacion"),
            entry("Copy the authorization code manually and press Cmd+C, then Enter.", "Copiez manuellement le code d'autorisation puis appuyez sur Cmd+C, puis Entree.", "Kopieren Sie den Autorisierungscode manuell und druecken Sie Cmd+C, dann Enter.", "Copie manualmente o codigo de autorizacao e prima Cmd+C, depois Enter.", "Copie manualmente o codigo de autorizacao e pressione Cmd+C, depois Enter.", "Copie manualmente el codigo de autorizacion y pulse Cmd+C, luego Enter."),
            entry("Clipboard access was blocked by the browser. A manual copy dialog was opened with the authorization code.", "L'acces au presse-papiers a ete bloque par le navigateur. Une boite de dialogue de copie manuelle a ete ouverte avec le code d'autorisation.", "Der Zugriff auf die Zwischenablage wurde vom Browser blockiert. Ein Dialog fuer das manuelle Kopieren mit dem Autorisierungscode wurde geoeffnet.", "O acesso a area de transferencia foi bloqueado pelo browser. Foi aberta uma janela para copiar manualmente o codigo de autorizacao.", "O acesso a area de transferencia foi bloqueado pelo navegador. Foi aberta uma janela para copiar manualmente o codigo de autorizacao.", "El acceso al portapapeles fue bloqueado por el navegador. Se abrio un dialogo de copia manual con el codigo de autorizacion."),
            entry("No env assignment is available to copy yet.", "Aucune affectation d'environnement n'est encore disponible a copier.", "Es ist noch keine Umgebungszuweisung zum Kopieren verfuegbar.", "Ainda nao existe nenhuma atribuicao de ambiente disponivel para copiar.", "Ainda nao ha nenhuma atribuicao de ambiente disponivel para copiar.", "Todavia no hay ninguna asignacion de entorno disponible para copiar."),
            entry("Env assignment", "Affectation d'environnement", "Umgebungszuweisung", "Atribuicao de ambiente", "Atribuicao de ambiente", "Asignacion de entorno"),
            entry("Copy the env assignment manually and press Cmd+C, then Enter.", "Copiez manuellement l'affectation d'environnement puis appuyez sur Cmd+C, puis Entree.", "Kopieren Sie die Umgebungszuweisung manuell und druecken Sie Cmd+C, dann Enter.", "Copie manualmente a atribuicao de ambiente e prima Cmd+C, depois Enter.", "Copie manualmente a atribuicao de ambiente e pressione Cmd+C, depois Enter.", "Copie manualmente la asignacion de entorno y pulse Cmd+C, luego Enter."),
            entry("Clipboard access was blocked by the browser. A manual copy dialog was opened with the env assignment.", "L'acces au presse-papiers a ete bloque par le navigateur. Une boite de dialogue de copie manuelle a ete ouverte avec l'affectation d'environnement.", "Der Zugriff auf die Zwischenablage wurde vom Browser blockiert. Ein Dialog fuer das manuelle Kopieren mit der Umgebungszuweisung wurde geoeffnet.", "O acesso a area de transferencia foi bloqueado pelo browser. Foi aberta uma janela para copiar manualmente a atribuicao de ambiente.", "O acesso a area de transferencia foi bloqueado pelo navegador. Foi aberta uma janela para copiar manualmente a atribuicao de ambiente.", "El acceso al portapapeles fue bloqueado por el navegador. Se abrio un dialogo de copia manual con la asignacion de entorno."),
            entry("Exchange failed with status ", "L'echange a echoue avec le statut ", "Austausch fehlgeschlagen mit Status ", "A troca do codigo falhou com o estado ", "A troca do codigo falhou com o estado ", "El intercambio fallo con el estado "),
            entry(". Check the server logs and Microsoft app settings.", ". Verifiez les journaux du serveur et les parametres de l'application Microsoft.", ". Pruefen Sie die Serverprotokolle und die Microsoft-App-Einstellungen.", ". Verifique os logs do servidor e as definicoes da aplicacao Microsoft.", ". Verifique os logs do servidor e as definicoes da aplicacao Microsoft.", ". Revise los registros del servidor y la configuracion de la aplicacion de Microsoft."),
            entry("The callback state is missing or expired. Start the Microsoft OAuth flow again from InboxBridge.", "L'etat du rappel est absent ou a expire. Redemarrez le flux Microsoft OAuth depuis InboxBridge.", "Der Callback-Status fehlt oder ist abgelaufen. Starten Sie den Microsoft-OAuth-Ablauf erneut in InboxBridge.", "O estado do retorno esta em falta ou expirou. Inicie novamente o fluxo Microsoft OAuth a partir do InboxBridge.", "O estado do retorno esta faltando ou expirou. Inicie novamente o fluxo de Microsoft OAuth a partir do InboxBridge.", "El estado del retorno falta o caduco. Inicie de nuevo el flujo de Microsoft OAuth desde InboxBridge."),
            entry("Source ID: ", "ID de la source : ", "Quell-ID: ", "ID da conta: ", "ID da conta: ", "ID de la cuenta: "),
            entry("Secure storage", "Stockage securise", "Sichere Speicherung", "Armazenamento seguro", "Armazenamento seguro", "Almacenamiento seguro"),
            entry("Exchange completed, but this env-managed source cannot poll yet. Copy the env assignment into your local .env, restart InboxBridge, and then polling will be able to use the new refresh token.", "Echange termine, mais cette source geree par l'environnement ne peut pas encore interroger. Copiez l'affectation d'environnement dans votre .env local, redemarrez InboxBridge, puis l'interrogation pourra utiliser le nouveau jeton d'actualisation.", "Austausch abgeschlossen, aber diese umgebungsverwaltete Quelle kann noch nicht pollen. Kopieren Sie die Umgebungszuweisung in Ihre lokale .env, starten Sie InboxBridge neu, dann kann das Polling das neue Aktualisierungstoken verwenden.", "Troca concluida, mas esta conta gerida por ambiente ainda nao pode ser verificada. Copie a atribuicao para o seu .env local, reinicie o InboxBridge e a verificacao podera usar o novo refresh token.", "Troca concluida, mas esta conta gerenciada por ambiente ainda nao pode consultar. Copie a atribuicao para o seu .env local, reinicie o InboxBridge e a consulta podera usar o novo refresh token.", "Intercambio completado, pero esta fuente gestionada por entorno aun no puede sondear. Copie la asignacion de entorno en su .env local, reinicie InboxBridge y entonces el sondeo podra usar el nuevo token de actualizacion."),
            entry("Exchange completed. The refresh token was stored securely and future renewals will be automatic.", "Echange termine. Le jeton d'actualisation a ete stocke de maniere securisee et les renouvellements futurs seront automatiques.", "Austausch abgeschlossen. Das Aktualisierungstoken wurde sicher gespeichert und zukuenftige Erneuerungen erfolgen automatisch.", "Troca concluida. O refresh token foi guardado de forma segura e as futuras renovacoes serao automaticas.", "Troca concluida. O refresh token foi guardado de forma segura e as futuras renovacoes serao automaticas.", "Intercambio completado. El token de actualizacion se guardo de forma segura y las renovaciones futuras seran automaticas."),
            entry("Authorization code received, but callback state is missing. Start the Microsoft OAuth flow again if automatic exchange does not work.", "Code d'autorisation recu, mais l'etat du rappel manque. Redemarrez le flux Microsoft OAuth si l'echange automatique ne fonctionne pas.", "Autorisierungscode empfangen, aber der Callback-Status fehlt. Starten Sie den Microsoft-OAuth-Ablauf erneut, wenn der automatische Austausch nicht funktioniert.", "Codigo de autorizacao recebido, mas o estado do retorno esta em falta. Inicie novamente o fluxo Microsoft OAuth se a troca automatica nao funcionar.", "Codigo de autorizacao recebido, mas o estado do retorno esta faltando. Inicie novamente o fluxo de Microsoft OAuth se o intercambio automatico nao funcionar.", "Codigo de autorizacion recibido, pero falta el estado del retorno. Inicie de nuevo el flujo de Microsoft OAuth si el intercambio automatico no funciona."),
            entry("Leave this page without exchanging the code? If you continue, you must copy the code and handle the token exchange manually later.", "Quitter cette page sans echanger le code ? Si vous continuez, vous devrez copier le code et gerer manuellement l'echange du jeton plus tard.", "Diese Seite verlassen, ohne den Code auszutauschen? Wenn Sie fortfahren, muessen Sie den Code kopieren und den Token-Austausch spaeter manuell erledigen.", "Sair desta pagina sem trocar o codigo? Se continuar, tera de copiar o codigo e tratar manualmente da troca do token mais tarde.", "Sair desta pagina sem trocar o codigo? Se continuar, sera necessario copiar o codigo e tratar manualmente da troca do token depois.", "Salir de esta pagina sin intercambiar el codigo? Si continua, tendra que copiar el codigo y gestionar manualmente el intercambio del token mas tarde."),
            entry("Exchange the code in the browser before leaving, or copy it now and complete the token exchange manually later.", "Echangez le code dans le navigateur avant de quitter, ou copiez-le maintenant et terminez manuellement l'echange du jeton plus tard.", "Tauschen Sie den Code im Browser aus, bevor Sie die Seite verlassen, oder kopieren Sie ihn jetzt und schliessen Sie den Token-Austausch spaeter manuell ab.", "Troque o codigo no browser antes de sair, ou copie-o agora e conclua manualmente a troca do token mais tarde.", "Troque o codigo no navegador antes de sair, ou copie-o agora e conclua manualmente a troca do token depois.", "Intercambie el codigo en el navegador antes de salir, o copielo ahora y complete manualmente el intercambio del token mas tarde."),
            entry("You can close this tab after the exchange succeeds and any remaining setup is complete.", "Vous pouvez fermer cet onglet une fois l'echange reussi et toute configuration restante terminee.", "Sie koennen diesen Tab schliessen, nachdem der Austausch erfolgreich war und die verbleibende Einrichtung abgeschlossen ist.", "Pode fechar este separador depois de a troca ser concluida com sucesso e de qualquer configuracao restante ficar concluida.", "Voce pode fechar esta aba depois que a troca for concluida com sucesso e qualquer configuracao restante estiver completa.", "Puede cerrar esta pestana despues de que el intercambio termine correctamente y la configuracion restante se complete."),
            entry("Success", "Succes", "Erfolg", "Sucesso", "Sucesso", "Exito"),
            entry("Attention", "Attention", "Achtung", "Atencao", "Atencao", "Atencion"),
            entry("Microsoft OAuth Permission Required", "Autorisation Microsoft OAuth requise", "Microsoft-OAuth-Berechtigung erforderlich", "Permissao necessaria no Microsoft OAuth", "Permissao necessaria no Microsoft OAuth", "Permiso necesario en Microsoft OAuth"),
            entry("Microsoft OAuth Error", "Erreur Microsoft OAuth", "Microsoft-OAuth-Fehler", "Erro de Microsoft OAuth", "Erro de Microsoft OAuth", "Error de Microsoft OAuth"),
            entry("Microsoft OAuth did not receive the required consent. Retry the flow and approve every requested mailbox permission so InboxBridge can refresh tokens and read the source mailbox.", "Microsoft OAuth n'a pas recu le consentement requis. Relancez le flux et acceptez toutes les autorisations de boite mail demandees afin qu'InboxBridge puisse renouveler les jetons et lire la boite source.", "Microsoft OAuth hat die erforderliche Zustimmung nicht erhalten. Starten Sie den Ablauf erneut und genehmigen Sie alle angeforderten Postfach-Berechtigungen, damit InboxBridge Tokens erneuern und das Quellpostfach lesen kann.", "O Microsoft OAuth nao recebeu o consentimento necessario. Repita o processo e aceite todas as permissoes pedidas para a caixa de correio, para que o InboxBridge possa renovar tokens e ler a conta de origem.", "O Microsoft OAuth nao recebeu o consentimento necessario. Repita o processo e aceite todas as permissoes pedidas para a caixa de correio, para que o InboxBridge possa renovar tokens e ler a conta de origem.", "Microsoft OAuth no recibio el consentimiento necesario. Repita el proceso y acepte todos los permisos del buzon solicitados para que InboxBridge pueda renovar tokens y leer la cuenta de origen."),
            entry("The Microsoft authorization step failed. Retry the flow after correcting the Microsoft consent or app configuration.", "L'etape d'autorisation Microsoft a echoue. Relancez le flux apres avoir corrige le consentement Microsoft ou la configuration de l'application.", "Der Microsoft-Autorisierungsschritt ist fehlgeschlagen. Starten Sie den Ablauf erneut, nachdem Sie die Microsoft-Zustimmung oder die App-Konfiguration korrigiert haben.", "O passo de autorizacao da Microsoft falhou. Repita o processo depois de corrigir o consentimento Microsoft ou a configuracao da aplicacao.", "O passo de autorizacao da Microsoft falhou. Repita o processo depois de corrigir o consentimento Microsoft ou a configuracao da aplicacao.", "El paso de autorizacion de Microsoft fallo. Repita el proceso despues de corregir el consentimiento de Microsoft o la configuracion de la aplicacion."),
            entry("The Microsoft authorization step failed. Retry the flow and approve every requested permission.", "L'etape d'autorisation Microsoft a echoue. Relancez le flux et acceptez toutes les autorisations demandees.", "Der Microsoft-Autorisierungsschritt ist fehlgeschlagen. Starten Sie den Ablauf erneut und genehmigen Sie alle angeforderten Berechtigungen.", "O passo de autorizacao da Microsoft falhou. Repita o processo e aceite todas as permissoes pedidas.", "O passo de autorizacao da Microsoft falhou. Repita o processo e aceite todas as permissoes pedidas.", "El paso de autorizacion de Microsoft fallo. Repita el proceso y acepte todos los permisos solicitados."),
            entry("Code", "Code", "Code", "Codigo", "Codigo", "Codigo")
    );

    private OAuthPageI18n() {
    }

    public static String text(String language, String english) {
        String normalized = normalize(language);
        return TRANSLATIONS.getOrDefault(english, Map.of()).getOrDefault(normalized, english);
    }

    public static String normalize(String language) {
        if (language == null || language.isBlank()) {
            return "en";
        }
        String normalized = language.trim().toLowerCase();
        if ("fr".equals(normalized) || normalized.startsWith("fr-")) {
            return "fr";
        }
        if ("de".equals(normalized) || normalized.startsWith("de-")) {
            return "de";
        }
        if ("es".equals(normalized) || normalized.startsWith("es-")) {
            return "es";
        }
        if ("pt-br".equals(normalized)) {
            return "pt-BR";
        }
        if ("pt".equals(normalized) || normalized.startsWith("pt-")) {
            return "pt-PT";
        }
        return "en";
    }

    private static Map.Entry<String, Map<String, String>> entry(
            String english,
            String french,
            String german,
            String portuguesePortugal,
            String portugueseBrazil,
            String spanish) {
        return Map.entry(english, Map.of(
                "fr", french,
                "de", german,
                "pt-PT", portuguesePortugal,
                "pt-BR", portugueseBrazil,
                "es", spanish));
    }
}
