version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "java"

  - package-ecosystem: "npm"
    directory: "/admin-ui"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "frontend"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/admin-ui"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
