package dev.inboxbridge.web;

import java.util.Map;

final class OAuthPageI18n {

    private static final Map<String, Map<String, String>> TRANSLATIONS = Map.ofEntries(
            entry("Google OAuth Callback", "Retour OAuth Google", "Google OAuth-Rueckruf", "Retorno do Google OAuth", "Retorno do Google OAuth", "Retorno de Google OAuth"),
            entry("Google OAuth Code Received", "Code OAuth Google recu", "Google-OAuth-Code empfangen", "Codigo do Google OAuth recebido", "Codigo do Google OAuth recebido", "Codigo de Google OAuth recibido"),
            entry("Microsoft OAuth Code Received", "Code OAuth Microsoft recu", "Microsoft-OAuth-Code empfangen", "Codigo do Microsoft OAuth recebido", "Codigo do Microsoft OAuth recebido", "Codigo de Microsoft OAuth recibido"),
            entry("Copy Code", "Copier le code", "Code kopieren", "Copiar codigo", "Copiar codigo", "Copiar codigo"),
            entry("Exchange Code In Browser", "Echanger le code dans le navigateur", "Code im Browser austauschen", "Trocar codigo no browser", "Trocar codigo no browser", "Intercambiar codigo en el navegador"),
            entry("Return To Admin UI", "Retourner a l'interface d'administration", "Zur Admin-Oberflaeche zurueckkehren", "Voltar a interface de administracao", "Voltar para a interface de administracao", "Volver a la interfaz de administracion"),
            entry("(no authorization code received)", "(aucun code d'autorisation recu)", "(kein Autorisierungscode empfangen)", "(nenhum codigo de autorizacao recebido)", "(nenhum codigo de autorizacao recebido)", "(no se recibio ningun codigo de autorizacion)"),
            entry("Returning to the admin UI in ", "Retour a l'interface d'administration dans ", "Rueckkehr zur Admin-Oberflaeche in ", "A voltar para a interface de administracao em ", "Voltando para a interface de administracao em ", "Volviendo a la interfaz de administracion en "),
            entry(" seconds.", " secondes.", " Sekunden.", " segundos.", " segundos.", " segundos."),
            entry("Returning to the admin UI now...", "Retour a l'interface d'administration maintenant...", "Rueckkehr zur Admin-Oberflaeche jetzt...", "A voltar para a interface de administracao agora...", "Voltando para a interface de administracao agora...", "Volviendo a la interfaz de administracion ahora..."),
            entry("No authorization code is available to copy from this callback URL.", "Aucun code d'autorisation n'est disponible a copier depuis cette URL de retour.", "Es ist kein Autorisierungscode verfuegbar, der aus dieser Callback-URL kopiert werden kann.", "Nao existe nenhum codigo de autorizacao disponivel para copiar deste URL de retorno.", "Nao existe nenhum codigo de autorizacao disponivel para copiar desta URL de retorno.", "No hay ningun codigo de autorizacion disponible para copiar desde esta URL de retorno."),
            entry("Authorization code copied to clipboard.", "Code d'autorisation copie dans le presse-papiers.", "Autorisierungscode in die Zwischenablage kopiert.", "Codigo de autorizacao copiado para a area de transferencia.", "Codigo de autorizacao copiado para a area de transferencia.", "Codigo de autorizacion copiado al portapapeles."),
            entry("Unable to copy automatically. Copy the code manually before leaving this page.", "Copie automatique impossible. Copiez le code manuellement avant de quitter cette page.", "Automatisches Kopieren nicht moeglich. Kopieren Sie den Code manuell, bevor Sie diese Seite verlassen.", "Nao foi possivel copiar automaticamente. Copie o codigo manualmente antes de sair desta pagina.", "Nao foi possivel copiar automaticamente. Copie o codigo manualmente antes de sair desta pagina.", "No se pudo copiar automaticamente. Copie el codigo manualmente antes de salir de esta pagina."),
            entry("Google OAuth is still missing one or more required permissions. Retry the flow and approve every requested Gmail permission, then try again. Details: ", "Il manque encore une ou plusieurs autorisations requises a Google OAuth. Relancez le flux et acceptez toutes les autorisations Gmail demandees. Details : ", "Google OAuth fehlen weiterhin eine oder mehrere erforderliche Berechtigungen. Starten Sie den Vorgang erneut und genehmigen Sie alle angeforderten Gmail-Berechtigungen. Details: ", "Ainda falta uma ou mais permissoes obrigatorias no Google OAuth. Repita o processo e aceite todas as permissoes pedidas do Gmail. Detalhes: ", "Ainda falta uma ou mais permissoes obrigatorias no Google OAuth. Repita o processo e aceite todas as permissoes pedidas do Gmail. Detalhes: ", "A Google OAuth todavia le faltan uno o mas permisos obligatorios. Repita el proceso y acepte todos los permisos de Gmail solicitados. Detalles: "),
            entry("Microsoft OAuth is still missing one or more required permissions. Retry the flow and approve every requested mailbox permission, then try again. Details: ", "Il manque encore une ou plusieurs autorisations requises a Microsoft OAuth. Relancez le flux et acceptez toutes les autorisations de boite mail demandees. Details : ", "Microsoft OAuth fehlen weiterhin eine oder mehrere erforderliche Berechtigungen. Starten Sie den Vorgang erneut und genehmigen Sie alle angeforderten Postfach-Berechtigungen. Details: ", "Ainda falta uma ou mais permissoes obrigatorias no Microsoft OAuth. Repita o processo e aceite todas as permissoes pedidas da caixa de correio. Detalhes: ", "Ainda falta uma ou mais permissoes obrigatorias no Microsoft OAuth. Repita o processo e aceite todas as permissoes pedidas da caixa de correio. Detalhes: ", "A Microsoft OAuth todavia le faltan uno o mas permisos obligatorios. Repita el proceso y acepte todos los permisos del buzon solicitados. Detalles: "),
            entry("Exchange failed: ", "La conversion du code a echoue : ", "Der Code-Austausch ist fehlgeschlagen: ", "A troca do codigo falhou: ", "A troca do codigo falhou: ", "El intercambio del codigo fallo: "),
            entry("OAuth returned ", "OAuth a renvoye ", "OAuth gab zurueck ", "O OAuth devolveu ", "O OAuth devolveu ", "OAuth devolvio "),
            entry("Microsoft OAuth returned ", "Microsoft OAuth a renvoye ", "Microsoft OAuth gab zurueck ", "O Microsoft OAuth devolveu ", "O Microsoft OAuth devolveu ", "Microsoft OAuth devolvio "),
            entry("No authorization code was present in the callback URL.", "Aucun code d'autorisation n'etait present dans l'URL de retour.", "In der Callback-URL war kein Autorisierungscode vorhanden.", "Nao foi encontrado qualquer codigo de autorizacao no URL de retorno.", "Nao foi encontrado nenhum codigo de autorizacao na URL de retorno.", "No se encontro ningun codigo de autorizacion en la URL de retorno."),
            entry("Exchanging authorization code...", "Echange du code d'autorisation...", "Autorisierungscode wird ausgetauscht...", "A trocar o codigo de autorizacao...", "Trocando o codigo de autorizacao...", "Intercambiando el codigo de autorizacion..."),
            entry("Storage: ", "Armazenamento: ", "Speicher: ", "Armazenamento: ", "Armazenamento: ", "Almacenamiento: "),
            entry("Encrypted database", "Base de donnees chiffree", "Verschluesselte Datenbank", "Base de dados encriptada", "Banco de dados criptografado", "Base de datos cifrada"),
            entry("Environment fallback", "Repli sur l'environnement", "Umgebungs-Fallback", "Fallback por ambiente", "Fallback por ambiente", "Alternativa por entorno"),
            entry("Previous Gmail account replaced: ", "Compte Gmail precedent remplace : ", "Vorheriges Gmail-Konto ersetzt: ", "Conta Gmail anterior substituida: ", "Conta Gmail anterior substituida: ", "Cuenta de Gmail anterior sustituida: "),
            entry("Same Gmail account reauthorized: ", "Meme compte Gmail reautorise : ", "Dasselbe Gmail-Konto erneut autorisiert: ", "Mesma conta Gmail reautorizada: ", "Mesma conta Gmail reautorizada: ", "La misma cuenta de Gmail se volvio a autorizar: "),
            entry("Previous Google grant revoked: ", "Autorisation Google precedente revoquee : ", "Vorherige Google-Freigabe widerrufen: ", "Permissao Google anterior revogada: ", "Permissao Google anterior revogada: ", "Permiso de Google anterior revocado: "),
            entry("Yes", "Oui", "Ja", "Sim", "Sim", "Si"),
            entry("No", "Non", "Nein", "Nao", "Nao", "No"),
            entry("Credential Key: ", "Cle de credentiel : ", "Schluessel der Anmeldeinformation: ", "Chave da credencial: ", "Chave da credencial: ", "Clave de credencial: "),
            entry("Scope: ", "Portee : ", "Bereich: ", "Escopo: ", "Escopo: ", "Alcance: "),
            entry("Token Type: ", "Type de jeton : ", "Token-Typ: ", "Tipo de token: ", "Tipo de token: ", "Tipo de token: "),
            entry("Access Token Expires At: ", "Le jeton d'acces expire a : ", "Zugriffstoken laeuft ab am: ", "Token de acesso expira em: ", "Token de acesso expira em: ", "El token de acceso caduca en: "),
            entry("Next Step: ", "Etape suivante : ", "Naechster Schritt: ", "Proximo passo: ", "Proximo passo: ", "Paso siguiente: "),
            entry("Refresh Token: ", "Jeton d'actualisation : ", "Refresh-Token: ", "Refresh token: ", "Refresh token: ", "Token de actualizacion: "),
            entry("Exchange completed. The same Gmail account was reauthorized, so the existing Google grant was kept in place.", "Echange termine. Le meme compte Gmail a ete reautorise ; l'autorisation Google existante a donc ete conservee.", "Austausch abgeschlossen. Dasselbe Gmail-Konto wurde erneut autorisiert, daher blieb die bestehende Google-Freigabe erhalten.", "Troca concluida. A mesma conta Gmail foi reautorizada, por isso a permissao Google existente foi mantida.", "Troca concluida. A mesma conta Gmail foi reautorizada, por isso a permissao Google existente foi mantida.", "Intercambio concluido. Se volvio a autorizar la misma cuenta de Gmail, por lo que se mantuvo el permiso de Google existente."),
            entry("Exchange completed. Token stored encrypted in PostgreSQL. The previously linked Gmail account was automatically unlinked and its Google grant was revoked.", "Echange termine. Jeton stocke de maniere chiffree dans PostgreSQL. Le compte Gmail precedemment lie a ete dissocie automatiquement et son autorisation Google a ete revoquee.", "Austausch abgeschlossen. Token wurde verschluesselt in PostgreSQL gespeichert. Das zuvor verknuepfte Gmail-Konto wurde automatisch getrennt und seine Google-Freigabe widerrufen.", "Troca concluida. O token foi guardado de forma encriptada em PostgreSQL. A conta Gmail anteriormente ligada foi desligada automaticamente e a permissao Google foi revogada.", "Troca concluida. O token foi guardado de forma criptografada em PostgreSQL. A conta Gmail anteriormente vinculada foi desligada automaticamente e a permissao Google foi revogada.", "Intercambio concluido. El token se guardo cifrado en PostgreSQL. La cuenta de Gmail vinculada anteriormente se desvinculo automaticamente y su permiso de Google fue revocado."),
            entry("Exchange completed. Token stored encrypted in PostgreSQL. The previously linked Gmail account was replaced here, but you may still need to remove the old Google grant manually from myaccount.google.com.", "Echange termine. Jeton stocke de maniere chiffree dans PostgreSQL. Le compte Gmail precedemment lie a ete remplace ici, mais vous devrez peut-etre encore supprimer manuellement l'ancienne autorisation Google depuis myaccount.google.com.", "Austausch abgeschlossen. Token wurde verschluesselt in PostgreSQL gespeichert. Das zuvor verknuepfte Gmail-Konto wurde hier ersetzt, aber moeglicherweise muessen Sie die alte Google-Freigabe noch manuell unter myaccount.google.com entfernen.", "Troca concluida. O token foi guardado de forma encriptada em PostgreSQL. A conta Gmail anteriormente ligada foi substituida aqui, mas pode ainda ser necessario remover manualmente a permissao Google antiga em myaccount.google.com.", "Troca concluida. O token foi guardado de forma criptografada em PostgreSQL. A conta Gmail anteriormente vinculada foi substituida aqui, mas talvez ainda seja necessario remover manualmente a permissao Google antiga em myaccount.google.com.", "Intercambio concluido. El token se guardo cifrado en PostgreSQL. La cuenta de Gmail vinculada anteriormente se sustituyo aqui, pero quiza todavia necesite eliminar manualmente el permiso antiguo de Google en myaccount.google.com."),
            entry("Exchange completed. Token stored encrypted in PostgreSQL.", "Echange termine. Jeton stocke de maniere chiffree dans PostgreSQL.", "Austausch abgeschlossen. Token wurde verschluesselt in PostgreSQL gespeichert.", "Troca concluida. O token foi guardado de forma encriptada em PostgreSQL.", "Troca concluida. O token foi guardado de forma criptografada em PostgreSQL.", "Intercambio concluido. El token se guardo cifrado en PostgreSQL."),
            entry("Exchange completed. The same Gmail account was reauthorized. Copy the refresh token into your local .env if you are using env fallback.", "Echange termine. Le meme compte Gmail a ete reautorise. Copiez le refresh token dans votre .env local si vous utilisez le repli par environnement.", "Austausch abgeschlossen. Dasselbe Gmail-Konto wurde erneut autorisiert. Kopieren Sie das Refresh-Token in Ihre lokale .env, wenn Sie Umgebungs-Fallback verwenden.", "Troca concluida. A mesma conta Gmail foi reautorizada. Copie o refresh token para o seu .env local se estiver a usar fallback por ambiente.", "Troca concluida. A mesma conta Gmail foi reautorizada. Copie o refresh token para o seu .env local se estiver usando fallback por ambiente.", "Intercambio concluido. Se volvio a autorizar la misma cuenta de Gmail. Copie el refresh token a su .env local si esta usando alternativa por entorno."),
            entry("Exchange completed. The previously linked Gmail account was replaced. Copy the new refresh token into your local .env if you are using env fallback.", "Echange termine. Le compte Gmail precedemment lie a ete remplace. Copiez le nouveau refresh token dans votre .env local si vous utilisez le repli par environnement.", "Austausch abgeschlossen. Das zuvor verknuepfte Gmail-Konto wurde ersetzt. Kopieren Sie das neue Refresh-Token in Ihre lokale .env, wenn Sie Umgebungs-Fallback verwenden.", "Troca concluida. A conta Gmail anteriormente ligada foi substituida. Copie o novo refresh token para o seu .env local se estiver a usar fallback por ambiente.", "Troca concluida. A conta Gmail anteriormente vinculada foi substituida. Copie o novo refresh token para o seu .env local se estiver usando fallback por ambiente.", "Intercambio concluido. La cuenta de Gmail vinculada anteriormente fue sustituida. Copie el nuevo refresh token a su .env local si esta usando alternativa por entorno."),
            entry("Exchange completed. Copy the refresh token into your local .env if you are using env fallback.", "Echange termine. Copiez le refresh token dans votre .env local si vous utilisez le repli par environnement.", "Austausch abgeschlossen. Kopieren Sie das Refresh-Token in Ihre lokale .env, wenn Sie Umgebungs-Fallback verwenden.", "Troca concluida. Copie o refresh token para o seu .env local se estiver a usar fallback por ambiente.", "Troca concluida. Copie o refresh token para o seu .env local se estiver usando fallback por ambiente.", "Intercambio concluido. Copie el refresh token a su .env local si esta usando alternativa por entorno."),
            entry("Exchange failed. Check the server logs and OAuth client settings.", "L'echange a echoue. Verifiez les journaux du serveur et les parametres du client OAuth.", "Austausch fehlgeschlagen. Pruefen Sie die Serverprotokolle und die Einstellungen des OAuth-Clients.", "A troca do codigo falhou. Verifique os logs do servidor e as definicoes do cliente OAuth.", "A troca do codigo falhou. Verifique os logs do servidor e as configuracoes do cliente OAuth.", "El intercambio fallo. Revise los registros del servidor y la configuracion del cliente OAuth."),
            entry("Authorization code received. Attempting automatic exchange...", "Code d'autorisation recu. Tentative d'echange automatique...", "Autorisierungscode empfangen. Automatischer Austausch wird versucht...", "Codigo de autorizacao recebido. A tentar a troca automatica...", "Codigo de autorizacao recebido. Tentando a troca automatica...", "Codigo de autorizacion recibido. Intentando el intercambio automatico..."),
            entry("Authorization code received, but callback state is missing. Use the exchange button if you are completing a manual flow.", "Code d'autorisation recu, mais l'etat du retour manque. Utilisez le bouton d'echange si vous terminez un flux manuel.", "Autorisierungscode empfangen, aber der Callback-Status fehlt. Verwenden Sie die Austausch-Schaltflaeche, wenn Sie einen manuellen Ablauf abschliessen.", "Codigo de autorizacao recebido, mas o estado do retorno esta em falta. Use o botao de troca se estiver a completar um processo manual.", "Codigo de autorizacao recebido, mas o estado do retorno esta faltando. Use o botao de troca se estiver concluindo um fluxo manual.", "Codigo de autorizacion recibido, pero falta el estado del retorno. Use el boton de intercambio si esta completando un flujo manual."),
            entry("Leave this page without exchanging the code? You will need to add it manually later.", "Quitter cette page sans echanger le code ? Vous devrez l'ajouter manuellement plus tard.", "Diese Seite verlassen, ohne den Code auszutauschen? Sie muessen ihn spaeter manuell hinzufuegen.", "Sair desta pagina sem trocar o codigo? Vai ter de o adicionar manualmente mais tarde.", "Sair desta pagina sem trocar o codigo? Voce precisara adiciona-lo manualmente depois.", "Salir de esta pagina sin intercambiar el codigo? Tendra que anadirlo manualmente mas tarde."),
            entry("Leave this page without exchanging the code? If you continue, you will need to add it manually from the admin UI later.", "Quitter cette page sans echanger le code ? Si vous continuez, vous devrez l'ajouter manuellement depuis l'interface d'administration plus tard.", "Diese Seite verlassen, ohne den Code auszutauschen? Wenn Sie fortfahren, muessen Sie ihn spaeter manuell ueber die Admin-Oberflaeche hinzufuegen.", "Sair desta pagina sem trocar o codigo? Se continuar, vai ter de o adicionar manualmente mais tarde a partir da interface de administracao.", "Sair desta pagina sem trocar o codigo? Se continuar, voce precisara adiciona-lo manualmente depois a partir da interface de administracao.", "Salir de esta pagina sin intercambiar el codigo? Si continua, tendra que anadirlo manualmente mas tarde desde la interfaz de administracion."),
            entry("Exchange the code here, or copy it before leaving so you can add it manually later.", "Echangez le code ici, ou copiez-le avant de quitter pour pouvoir l'ajouter manuellement plus tard.", "Tauschen Sie den Code hier aus oder kopieren Sie ihn vor dem Verlassen, damit Sie ihn spaeter manuell hinzufuegen koennen.", "Troque o codigo aqui, ou copie-o antes de sair para o poder adicionar manualmente mais tarde.", "Troque o codigo aqui, ou copie-o antes de sair para poder adiciona-lo manualmente depois.", "Intercambie el codigo aqui o copielo antes de salir para poder anadirlo manualmente mas tarde."),
            entry("Error", "Erreur", "Fehler", "Erro", "Erro", "Error"),
            entry("Description", "Description", "Beschreibung", "Descricao", "Descricao", "Descripcion"),
            entry("Google OAuth Permission Required", "Autorisation Google OAuth requise", "Google-OAuth-Berechtigung erforderlich", "Permissao necessaria no Google OAuth", "Permissao necessaria no Google OAuth", "Permiso necesario en Google OAuth"),
            entry("Google OAuth Error", "Erreur Google OAuth", "Google-OAuth-Fehler", "Erro de Google OAuth", "Erro de Google OAuth", "Error de Google OAuth"),
            entry("Google OAuth did not receive the required consent. Retry the flow and approve every requested Gmail permission so InboxBridge can write imported mail and labels.", "Google OAuth n'a pas recu le consentement requis. Relancez le flux et acceptez toutes les autorisations Gmail demandees afin qu'InboxBridge puisse ecrire les emails et les libelles importes.", "Google OAuth hat die erforderliche Zustimmung nicht erhalten. Starten Sie den Ablauf erneut und genehmigen Sie alle angeforderten Gmail-Berechtigungen, damit InboxBridge importierte E-Mails und Labels schreiben kann.", "O Google OAuth nao recebeu o consentimento necessario. Repita o processo e aceite todas as permissoes pedidas do Gmail para que o InboxBridge possa gravar emails importados e etiquetas.", "O Google OAuth nao recebeu o consentimento necessario. Repita o processo e aceite todas as permissoes pedidas do Gmail para que o InboxBridge possa gravar emails importados e etiquetas.", "Google OAuth no recibio el consentimiento necesario. Repita el proceso y acepte todos los permisos de Gmail solicitados para que InboxBridge pueda escribir correos y etiquetas importados."),
            entry("Google OAuth returned an error. Retry the flow after correcting the Google consent or OAuth app configuration.", "Google OAuth a renvoye une erreur. Relancez le flux apres avoir corrige le consentement Google ou la configuration de l'application OAuth.", "Google OAuth hat einen Fehler zurueckgegeben. Starten Sie den Ablauf erneut, nachdem Sie die Google-Zustimmung oder die OAuth-App-Konfiguration korrigiert haben.", "O Google OAuth devolveu um erro. Repita o processo depois de corrigir o consentimento Google ou a configuracao da aplicacao OAuth.", "O Google OAuth devolveu um erro. Repita o processo depois de corrigir o consentimento Google ou a configuracao da aplicacao OAuth.", "Google OAuth devolvio un error. Repita el proceso despues de corregir el consentimiento de Google o la configuracion de la aplicacion OAuth."),
            entry("Google OAuth returned an error. Retry the flow and make sure every requested permission is approved.", "Google OAuth a renvoye une erreur. Relancez le flux et assurez-vous que toutes les autorisations demandees sont approuvees.", "Google OAuth hat einen Fehler zurueckgegeben. Starten Sie den Ablauf erneut und stellen Sie sicher, dass alle angeforderten Berechtigungen genehmigt werden.", "O Google OAuth devolveu um erro. Repita o processo e garanta que todas as permissoes pedidas sao aceites.", "O Google OAuth devolveu um erro. Repita o processo e garanta que todas as permissoes pedidas sejam aceitas.", "Google OAuth devolvio un error. Repita el proceso y asegurese de que todos los permisos solicitados sean aceptados."),
            entry("Invalid OAuth State", "Etat OAuth invalide", "Ungueltiger OAuth-Status", "Estado OAuth invalido", "Estado OAuth invalido", "Estado OAuth invalido"),
            entry("The callback state was missing or expired. Start the Microsoft OAuth flow again from the admin UI.", "L'etat du retour etait absent ou a expire. Relancez le flux Microsoft OAuth depuis l'interface d'administration.", "Der Callback-Status fehlte oder ist abgelaufen. Starten Sie den Microsoft-OAuth-Ablauf erneut ueber die Admin-Oberflaeche.", "O estado do retorno estava em falta ou expirou. Inicie novamente o fluxo Microsoft OAuth a partir da interface de administracao.", "O estado do retorno estava faltando ou expirou. Inicie novamente o fluxo Microsoft OAuth a partir da interface de administracao.", "Faltaba el estado de retorno o habia caducado. Inicie de nuevo el flujo de Microsoft OAuth desde la interfaz de administracion."),
            entry("You can exchange this authorization code directly in the browser. If secure token storage is configured, InboxBridge will save it encrypted in PostgreSQL and renew access tokens automatically.", "Vous pouvez echanger ce code d'autorisation directement dans le navigateur. Si le stockage securise des jetons est configure, InboxBridge l'enregistrera de maniere chiffree dans PostgreSQL et renouvellera automatiquement les jetons d'acces.", "Sie koennen diesen Autorisierungscode direkt im Browser austauschen. Wenn eine sichere Token-Speicherung konfiguriert ist, speichert InboxBridge ihn verschluesselt in PostgreSQL und erneuert Zugriffstoken automatisch.", "Pode trocar este codigo de autorizacao diretamente no browser. Se o armazenamento seguro de tokens estiver configurado, o InboxBridge vai guarda-lo de forma encriptada em PostgreSQL e renovar automaticamente os tokens de acesso.", "Voce pode trocar este codigo de autorizacao diretamente no navegador. Se o armazenamento seguro de tokens estiver configurado, o InboxBridge vai guarda-lo de forma criptografada em PostgreSQL e renovar automaticamente os tokens de acesso.", "Puede intercambiar este codigo de autorizacion directamente en el navegador. Si el almacenamiento seguro de tokens esta configurado, InboxBridge lo guardara cifrado en PostgreSQL y renovara automaticamente los tokens de acceso."),
            entry("Source ID", "ID de la source", "Quell-ID", "ID da conta", "ID da conta", "ID de la cuenta"),
            entry("Config Key", "Cle de configuration", "Konfigurationsschluessel", "Chave de configuracao", "Chave de configuracao", "Clave de configuracion"),
            entry("Env Refresh Token Key", "Cle du refresh token d'environnement", "Umgebungs-Refresh-Token-Schluessel", "Chave de refresh token do ambiente", "Chave de refresh token do ambiente", "Clave del refresh token del entorno"),
            entry("Authorization Code", "Code d'autorisation", "Autorisierungscode", "Codigo de autorizacao", "Codigo de autorizacao", "Codigo de autorizacion"),
            entry("Exchange Endpoint", "Point de terminaison d'echange", "Austausch-Endpunkt", "Endpoint de troca", "Endpoint de troca", "Endpoint de intercambio"),
            entry("Exchange Result", "Resultat de l'echange", "Austauschergebnis", "Resultado da troca", "Resultado da troca", "Resultado del intercambio"),
            entry("Env Assignment", "Attribution d'environnement", "Umgebungszuweisung", "Atribuicao de ambiente", "Atribuicao de ambiente", "Asignacion de entorno"),
            entry("Copy Env Assignment", "Copier l'attribution d'environnement", "Umgebungszuweisung kopieren", "Copiar atribuicao de ambiente", "Copiar atribuicao de ambiente", "Copiar asignacion de entorno"),
            entry(" copied to clipboard.", " copie dans le presse-papiers.", " in die Zwischenablage kopiert.", " copiado para a area de transferencia.", " copiado para a area de transferencia.", " copiado al portapapeles."),
            entry("Authorization code", "Code d'autorisation", "Autorisierungscode", "Codigo de autorizacao", "Codigo de autorizacao", "Codigo de autorizacion"),
            entry("Unable to copy the authorization code automatically.", "Impossible de copier automatiquement le code d'autorisation.", "Der Autorisierungscode konnte nicht automatisch kopiert werden.", "Nao foi possivel copiar automaticamente o codigo de autorizacao.", "Nao foi possivel copiar automaticamente o codigo de autorizacao.", "No se pudo copiar automaticamente el codigo de autorizacion."),
            entry("Env assignment", "Attribution d'environnement", "Umgebungszuweisung", "Atribuicao de ambiente", "Atribuicao de ambiente", "Asignacion de entorno"),
            entry("Unable to copy the env assignment automatically.", "Impossible de copier automatiquement l'attribution d'environnement.", "Die Umgebungszuweisung konnte nicht automatisch kopiert werden.", "Nao foi possivel copiar automaticamente a atribuicao de ambiente.", "Nao foi possivel copiar automaticamente a atribuicao de ambiente.", "No se pudo copiar automaticamente la asignacion de entorno."),
            entry("Exchange failed with status ", "L'echange a echoue avec le statut ", "Austausch fehlgeschlagen mit Status ", "A troca do codigo falhou com o estado ", "A troca do codigo falhou com o estado ", "El intercambio fallo con el estado "),
            entry(". Check the server logs and Microsoft app settings.", ". Verifiez les journaux du serveur et les parametres de l'application Microsoft.", ". Pruefen Sie die Serverprotokolle und die Einstellungen der Microsoft-App.", ". Verifique os logs do servidor e as definicoes da aplicacao Microsoft.", ". Verifique os logs do servidor e as configuracoes da aplicacao Microsoft.", ". Revise los registros del servidor y la configuracion de la aplicacion de Microsoft."),
            entry("The callback state is missing or expired. Start the Microsoft OAuth flow again from the admin UI.", "L'etat du retour manque ou a expire. Relancez le flux Microsoft OAuth depuis l'interface d'administration.", "Der Callback-Status fehlt oder ist abgelaufen. Starten Sie den Microsoft-OAuth-Ablauf erneut ueber die Admin-Oberflaeche.", "O estado do retorno esta em falta ou expirou. Inicie novamente o fluxo Microsoft OAuth a partir da interface de administracao.", "O estado do retorno esta faltando ou expirou. Inicie novamente o fluxo Microsoft OAuth a partir da interface de administracao.", "Falta el estado de retorno o ha caducado. Inicie de nuevo el flujo de Microsoft OAuth desde la interfaz de administracion."),
            entry("Exchange completed, but this env-managed source cannot poll yet. Copy the env assignment into your local .env, restart InboxBridge, and then polling will be able to use the new refresh token.", "Echange termine, mais cette source geree par l'environnement ne peut pas encore etre sondee. Copiez l'attribution dans votre .env local, redemarrez InboxBridge, puis la sonde pourra utiliser le nouveau refresh token.", "Austausch abgeschlossen, aber diese umgebungsverwaltete Quelle kann noch nicht pollen. Kopieren Sie die Zuweisung in Ihre lokale .env, starten Sie InboxBridge neu und dann kann das Polling das neue Refresh-Token verwenden.", "Troca concluida, mas esta conta gerida por ambiente ainda nao pode ser verificada. Copie a atribuicao para o seu .env local, reinicie o InboxBridge e a verificacao podera usar o novo refresh token.", "Troca concluida, mas esta conta gerida por ambiente ainda nao pode ser verificada. Copie a atribuicao para o seu .env local, reinicie o InboxBridge e a verificacao podera usar o novo refresh token.", "Intercambio concluido, pero esta cuenta gestionada por entorno todavia no puede verificarse. Copie la asignacion en su .env local, reinicie InboxBridge y entonces la verificacion podra usar el nuevo refresh token."),
            entry("Exchange completed. The refresh token was stored encrypted in PostgreSQL and future renewals will be automatic.", "Echange termine. Le refresh token a ete stocke de maniere chiffree dans PostgreSQL et les renouvellements futurs seront automatiques.", "Austausch abgeschlossen. Das Refresh-Token wurde verschluesselt in PostgreSQL gespeichert und kuenftige Erneuerungen erfolgen automatisch.", "Troca concluida. O refresh token foi guardado de forma encriptada em PostgreSQL e as futuras renovacoes serao automaticas.", "Troca concluida. O refresh token foi guardado de forma criptografada em PostgreSQL e as futuras renovacoes serao automaticas.", "Intercambio concluido. El refresh token se guardo cifrado en PostgreSQL y las renovaciones futuras seran automaticas."),
            entry("Authorization code received, but callback state is missing. Start the Microsoft OAuth flow again if automatic exchange does not work.", "Code d'autorisation recu, mais l'etat du retour manque. Relancez le flux Microsoft OAuth si l'echange automatique ne fonctionne pas.", "Autorisierungscode empfangen, aber der Callback-Status fehlt. Starten Sie den Microsoft-OAuth-Ablauf erneut, wenn der automatische Austausch nicht funktioniert.", "Codigo de autorizacao recebido, mas o estado do retorno esta em falta. Inicie novamente o fluxo Microsoft OAuth se a troca automatica nao funcionar.", "Codigo de autorizacao recebido, mas o estado do retorno esta faltando. Inicie novamente o fluxo Microsoft OAuth se a troca automatica nao funcionar.", "Codigo de autorizacion recibido, pero falta el estado del retorno. Inicie de nuevo el flujo de Microsoft OAuth si el intercambio automatico no funciona."),
            entry("Leave this page without exchanging the code? If you continue, you must copy the code and handle the token exchange manually later.", "Quitter cette page sans echanger le code ? Si vous continuez, vous devrez copier le code et gerer manuellement l'echange du jeton plus tard.", "Diese Seite verlassen, ohne den Code auszutauschen? Wenn Sie fortfahren, muessen Sie den Code kopieren und den Token-Austausch spaeter manuell erledigen.", "Sair desta pagina sem trocar o codigo? Se continuar, tera de copiar o codigo e tratar manualmente da troca do token mais tarde.", "Sair desta pagina sem trocar o codigo? Se continuar, sera necessario copiar o codigo e tratar manualmente da troca do token depois.", "Salir de esta pagina sin intercambiar el codigo? Si continua, tendra que copiar el codigo y gestionar manualmente el intercambio del token mas tarde."),
            entry("Exchange the code in the browser before leaving, or copy it now and complete the token exchange manually later.", "Echangez le code dans le navigateur avant de quitter, ou copiez-le maintenant et terminez manuellement l'echange du jeton plus tard.", "Tauschen Sie den Code im Browser aus, bevor Sie die Seite verlassen, oder kopieren Sie ihn jetzt und schliessen Sie den Token-Austausch spaeter manuell ab.", "Troque o codigo no browser antes de sair, ou copie-o agora e conclua manualmente a troca do token mais tarde.", "Troque o codigo no navegador antes de sair, ou copie-o agora e conclua manualmente a troca do token depois.", "Intercambie el codigo en el navegador antes de salir, o copielo ahora y complete manualmente el intercambio del token mas tarde."),
            entry("You can close this tab after the exchange succeeds and any remaining setup is complete.", "Vous pouvez fermer cet onglet une fois l'echange reussi et toute configuration restante terminee.", "Sie koennen diesen Tab schliessen, nachdem der Austausch erfolgreich war und die verbleibende Einrichtung abgeschlossen ist.", "Pode fechar este separador depois de a troca ser concluida com sucesso e de qualquer configuracao restante ficar concluida.", "Voce pode fechar esta aba depois que a troca for concluida com sucesso e qualquer configuracao restante estiver completa.", "Puede cerrar esta pestana despues de que el intercambio termine correctamente y la configuracion restante se complete."),
            entry("Success", "Succes", "Erfolg", "Sucesso", "Sucesso", "Exito"),
            entry("Attention", "Attention", "Achtung", "Atencao", "Atencao", "Atencion"),
            entry("Microsoft OAuth Permission Required", "Autorisation Microsoft OAuth requise", "Microsoft-OAuth-Berechtigung erforderlich", "Permissao necessaria no Microsoft OAuth", "Permissao necessaria no Microsoft OAuth", "Permiso necesario en Microsoft OAuth"),
            entry("Microsoft OAuth Error", "Erreur Microsoft OAuth", "Microsoft-OAuth-Fehler", "Erro de Microsoft OAuth", "Erro de Microsoft OAuth", "Error de Microsoft OAuth"),
            entry("Microsoft OAuth did not receive the required consent. Retry the flow and approve every requested mailbox permission so InboxBridge can refresh tokens and read the source mailbox.", "Microsoft OAuth n'a pas recu le consentement requis. Relancez le flux et acceptez toutes les autorisations de boite mail demandees afin qu'InboxBridge puisse renouveler les jetons et lire la boite source.", "Microsoft OAuth hat die erforderliche Zustimmung nicht erhalten. Starten Sie den Ablauf erneut und genehmigen Sie alle angeforderten Postfach-Berechtigungen, damit InboxBridge Tokens erneuern und das Quellpostfach lesen kann.", "O Microsoft OAuth nao recebeu o consentimento necessario. Repita o processo e aceite todas as permissoes pedidas para a caixa de correio, para que o InboxBridge possa renovar tokens e ler a conta de origem.", "O Microsoft OAuth nao recebeu o consentimento necessario. Repita o processo e aceite todas as permissoes pedidas para a caixa de correio, para que o InboxBridge possa renovar tokens e ler a conta de origem.", "Microsoft OAuth no recibio el consentimiento necesario. Repita el proceso y acepte todos los permisos del buzon solicitados para que InboxBridge pueda renovar tokens y leer la cuenta de origen."),
            entry("The Microsoft authorization step failed. Retry the flow after correcting the Microsoft consent or app configuration.", "L'etape d'autorisation Microsoft a echoue. Relancez le flux apres avoir corrige le consentement Microsoft ou la configuration de l'application.", "Der Microsoft-Autorisierungsschritt ist fehlgeschlagen. Starten Sie den Ablauf erneut, nachdem Sie die Microsoft-Zustimmung oder die App-Konfiguration korrigiert haben.", "O passo de autorizacao da Microsoft falhou. Repita o processo depois de corrigir o consentimento Microsoft ou a configuracao da aplicacao.", "O passo de autorizacao da Microsoft falhou. Repita o processo depois de corrigir o consentimento Microsoft ou a configuracao da aplicacao.", "El paso de autorizacion de Microsoft fallo. Repita el proceso despues de corregir el consentimiento de Microsoft o la configuracion de la aplicacion."),
            entry("The Microsoft authorization step failed. Retry the flow and approve every requested permission.", "L'etape d'autorisation Microsoft a echoue. Relancez le flux et acceptez toutes les autorisations demandees.", "Der Microsoft-Autorisierungsschritt ist fehlgeschlagen. Starten Sie den Ablauf erneut und genehmigen Sie alle angeforderten Berechtigungen.", "O passo de autorizacao da Microsoft falhou. Repita o processo e aceite todas as permissoes pedidas.", "O passo de autorizacao da Microsoft falhou. Repita o processo e aceite todas as permissoes pedidas.", "El paso de autorizacion de Microsoft fallo. Repita el proceso y acepte todos los permisos solicitados."),
            entry("Code", "Code", "Code", "Codigo", "Codigo", "Codigo")
    );

    private OAuthPageI18n() {
    }

    static String text(String language, String english) {
        String normalized = normalize(language);
        return TRANSLATIONS.getOrDefault(english, Map.of()).getOrDefault(normalized, english);
    }

    static String normalize(String language) {
        if (language == null || language.isBlank()) {
            return "en";
        }
        String normalized = language.trim().toLowerCase();
        if ("fr".equals(normalized) || normalized.startsWith("fr-")) {
            return "fr";
        }
        if ("de".equals(normalized) || normalized.startsWith("de-")) {
            return "de";
        }
        if ("es".equals(normalized) || normalized.startsWith("es-")) {
            return "es";
        }
        if ("pt-br".equals(normalized)) {
            return "pt-BR";
        }
        if ("pt".equals(normalized) || normalized.startsWith("pt-")) {
            return "pt-PT";
        }
        return "en";
    }

    private static Map.Entry<String, Map<String, String>> entry(
            String english,
            String french,
            String german,
            String portuguesePortugal,
            String portugueseBrazil,
            String spanish) {
        return Map.entry(english, Map.of(
                "fr", french,
                "de", german,
                "pt-PT", portuguesePortugal,
                "pt-BR", portugueseBrazil,
                "es", spanish));
    }
}
