package dev.inboxbridge.dto;

/**
 * Describes effective authentication abuse-protection behavior together with
 * env defaults and optional admin-managed overrides.
 */
public record AuthSecuritySettingsView(
        int defaultLoginFailureThreshold,
        Integer loginFailureThresholdOverride,
        int effectiveLoginFailureThreshold,
        String defaultLoginInitialBlock,
        String loginInitialBlockOverride,
        String effectiveLoginInitialBlock,
        String defaultLoginMaxBlock,
        String loginMaxBlockOverride,
        String effectiveLoginMaxBlock,
        boolean defaultRegistrationChallengeEnabled,
        Boolean registrationChallengeEnabledOverride,
        boolean effectiveRegistrationChallengeEnabled,
        String defaultRegistrationChallengeTtl,
        String registrationChallengeTtlOverride,
        String effectiveRegistrationChallengeTtl,
        String defaultRegistrationChallengeProvider,
        String registrationChallengeProviderOverride,
        String effectiveRegistrationChallengeProvider,
        String availableRegistrationCaptchaProviders,
        String defaultRegistrationTurnstileSiteKey,
        String registrationTurnstileSiteKeyOverride,
        boolean registrationTurnstileConfigured,
        String defaultRegistrationHcaptchaSiteKey,
        String registrationHcaptchaSiteKeyOverride,
        boolean registrationHcaptchaConfigured,
        boolean defaultGeoIpEnabled,
        Boolean geoIpEnabledOverride,
        boolean effectiveGeoIpEnabled,
        String defaultGeoIpPrimaryProvider,
        String geoIpPrimaryProviderOverride,
        String effectiveGeoIpPrimaryProvider,
        String defaultGeoIpFallbackProviders,
        String geoIpFallbackProvidersOverride,
        String effectiveGeoIpFallbackProviders,
        String defaultGeoIpCacheTtl,
        String geoIpCacheTtlOverride,
        String effectiveGeoIpCacheTtl,
        String defaultGeoIpProviderCooldown,
        String geoIpProviderCooldownOverride,
        String effectiveGeoIpProviderCooldown,
        String defaultGeoIpRequestTimeout,
        String geoIpRequestTimeoutOverride,
        String effectiveGeoIpRequestTimeout,
        String availableGeoIpProviders,
        boolean geoIpIpinfoTokenConfigured,
        boolean secureStorageConfigured) {
}
