package dev.inboxbridge.dto;

public record EmailAccountConnectionTestResult(
        boolean success,
        String message,
        String protocol,
        String host,
        int port,
        boolean tls,
        String authMethod,
        String oauthProvider,
        boolean authenticated,
        String folder,
        boolean folderAccessible,
        boolean unreadFilterRequested,
        Boolean unreadFilterSupported,
        Boolean unreadFilterValidated,
        Integer visibleMessageCount,
        Integer unreadMessageCount,
        Boolean sampleMessageAvailable,
        Boolean sampleMessageMaterialized,
        Boolean forwardedMarkerSupported,
        Boolean tlsAvailable,
        Boolean tlsRecommended,
        Integer recommendedTlsPort,
        String transportSecurityWarning) {

    public EmailAccountConnectionTestResult(
            boolean success,
            String message,
            String protocol,
            String host,
            int port,
            boolean tls,
            String authMethod,
            String oauthProvider,
            boolean authenticated,
            String folder,
            boolean folderAccessible,
            boolean unreadFilterRequested,
            Boolean unreadFilterSupported,
            Boolean unreadFilterValidated,
            Integer visibleMessageCount,
            Integer unreadMessageCount,
            Boolean sampleMessageAvailable,
            Boolean sampleMessageMaterialized,
            Boolean forwardedMarkerSupported) {
        this(
                success,
                message,
                protocol,
                host,
                port,
                tls,
                authMethod,
                oauthProvider,
                authenticated,
                folder,
                folderAccessible,
                unreadFilterRequested,
                unreadFilterSupported,
                unreadFilterValidated,
                visibleMessageCount,
                unreadMessageCount,
                sampleMessageAvailable,
                sampleMessageMaterialized,
                forwardedMarkerSupported,
                null,
                null,
                null,
                null);
    }
}
