package dev.inboxbridge.dto;

import java.time.Instant;

public record RemoteSourceView(
        String sourceId,
        String scope,
        Long ownerUserId,
        String ownerLabel,
        boolean enabled,
        boolean effectivePollEnabled,
        String effectivePollInterval,
        int effectiveFetchWindow,
        String protocol,
        String host,
        int port,
        String username,
        String folder,
        boolean unreadOnly,
        String customLabel,
        boolean markReadAfterPoll,
        String postPollAction,
        String postPollTargetFolder,
        long totalImportedMessages,
        Instant lastImportedAt,
        AdminPollEventSummary lastEvent,
        SourcePollingStateView pollingState) {

    public RemoteSourceView(
            String sourceId,
            String scope,
            Long ownerUserId,
            String ownerLabel,
            boolean enabled,
            boolean effectivePollEnabled,
            String effectivePollInterval,
            int effectiveFetchWindow,
            String protocol,
            String host,
            int port,
            String username,
            String folder,
            String customLabel,
            long totalImportedMessages,
            Instant lastImportedAt,
            AdminPollEventSummary lastEvent,
            SourcePollingStateView pollingState) {
        this(
                sourceId,
                scope,
                ownerUserId,
                ownerLabel,
                enabled,
                effectivePollEnabled,
                effectivePollInterval,
                effectiveFetchWindow,
                protocol,
                host,
                port,
                username,
                folder,
                false,
                customLabel,
                false,
                "NONE",
                "",
                totalImportedMessages,
                lastImportedAt,
                lastEvent,
                pollingState);
    }
}
