create table system_secret_retirement_review (
    id bigint generated by default as identity primary key,
    reviewed_at timestamp with time zone not null,
    reviewed_by_user_id bigint,
    reviewed_by_username varchar(120),
    provider_id varchar(64),
    active_key_version varchar(160),
    active_key_id varchar(160),
    legacy_key_ids_json text,
    safe_to_retire_legacy_keys boolean not null default false,
    legacy_key_retirement_ready boolean not null default false,
    non_active_key_record_count bigint not null default 0,
    unavailable_key_record_count bigint not null default 0,
    latest_request_status varchar(32),
    blocking_requirements_remaining integer not null default 0,
    unsatisfied_requirement_ids_json text,
    status_snapshot_json text not null
);

create index idx_system_secret_retirement_review_reviewed_at
    on system_secret_retirement_review (reviewed_at desc);
