create table system_secret_recovery_review (
    id bigint generated by default as identity primary key,
    reviewed_at timestamp with time zone not null,
    reviewed_by_user_id bigint,
    reviewed_by_username varchar(120),
    request_fingerprint varchar(255) not null,
    latest_request_status varchar(32),
    latest_request_message varchar(500),
    verification_passed boolean not null default false,
    rollback_recommended boolean not null default false,
    mode varchar(64),
    provider_id varchar(64),
    active_key_version varchar(160),
    provider_writable boolean not null default false,
    unavailable_key_record_count bigint not null default 0,
    status_snapshot_json text not null
);

create index idx_system_secret_recovery_review_reviewed_at
    on system_secret_recovery_review (reviewed_at desc);
